const mongoose =require('mongoose');

var CompanyDetails=mongoose.model('CompanyDetails',{
   
    organizationname:{
        type:String
    },
    companyname:{
        type:String
    },
    mobileno:{
        type:Number
    },
    email:{
        type:String
    },
    website:{
        type:String
    },
    country:{
        type:Number
    },
    state:{
        type:Number
    },
    address:{
        type:String
    },
    noofemployee:{
        type:Number
    },
    codestartswith:{
        type:String
    },
    biocodestartrange:{
        type:String
    },
    biocodeendrange:{
        type:String
    },
    companyregisterationnumber:{
        type:String
    },
    gstnumber:{
        type:String
    },
    chkbiometric:{
        type:String
    },
    chkgps:{
        type:String
    },
    chkManual:{
        type:String
    },
    myfile:{
        type:String
    },
    chkpp:{
        type:String
    },
    chkESIC:{
        type:String
    },
    chkpt:{
        type:String
    },
    chkLWF:{
        type:String
    },
    chkTDS:{
        type:String
    }
});
module.exports={CompanyDetails};